### ISSUE TITLE
Melpa package?

### ISSUE THREAD

**Issue by kir0ul** [jmpunkt/ox-typst#2]
Hello,
Thanks for this package!
I think it would be great if this could be added on [Melpa](https://melpa.org/). Is there any plan along those lines?

**Comment by jmpunkt** [comment]
Currently I am not planing to publish this package to Melpa. However, I will look into the process and check the requirements and implications of publishing to Melpa. Bringing this package to Melpa would probably simplify my configuration as well.

For now, the easiest way is to use a package manager which supports Git repos (e.g. straight). The snippet blow might work, I did **not** test it.

```elisp
;; THIS IS NOT TESTED
(use-package ox-typst
  :straight (ox-typst :host github :repo "jmpunkt/ox-typst"))
```

I use Nix to manage Emacs packages. Packages are manually added, which are only available through Git. For me, it is not that _urgent_ publishing  to Melpa, but would benefit me.

### Nix

For the interested, how to use it within Nix.

- Package defined [here](https://github.com/jmpunkt/nixos-conf/blob/d0f6c9a6e7cc25242d462edc3c5c9053056fed3e/pkgs/emacsPackages/ox-typst.nix)
- All Git Emacs packages are grouped [here](https://github.com/jmpunkt/nixos-conf/blob/d0f6c9a6e7cc25242d462edc3c5c9053056fed3e/pkgs/emacsPackages/default.nix)
- Overlay imports the grouped packages [here](https://github.com/jmpunkt/nixos-conf/blob/d0f6c9a6e7cc25242d462edc3c5c9053056fed3e/overlays/10-pkgs.nix#L19)
- Imported into the Emacs derivation [here](https://github.com/jmpunkt/nixos-conf/blob/d0f6c9a6e7cc25242d462edc3c5c9053056fed3e/pkgs/applications/emacs/packages.nix#L65) and [here](https://github.com/jmpunkt/nixos-conf/blob/d0f6c9a6e7cc25242d462edc3c5c9053056fed3e/pkgs/applications/emacs/default.nix#L6)

**Comment by antoniocorbi** [comment]
Hi!
This package is super-useful!
Any chance to publish into Melpa?

**Comment by jmpunkt** [comment]
https://github.com/melpa/melpa/pull/9243

**Comment by jmpunkt** [comment]
The PR was merged. The package should be available soon through Melpa.

**Comment by antoniocorbi** [comment]
> The PR was merged. The package should be available soon through Melpa.

I can confirm that it's yet available on Melpa.
Thanks for your work and providing us with it @jmpunkt !
